const fs = require('fs');
const content = fs.readFileSync('src/WelcomeScreen.tsx', 'utf-8');
const target = `    setMovingProjectId(null);
    await loadData();
    setToastMsg(t(lang, 'projectMoved') || 'Project moved successfully');`;
const replacement = `    setMovingProjectId(null);
    await loadData();
    if (onReloadProjects) onReloadProjects();
    setToastMsg(t(lang, 'projectMoved') || 'Project moved successfully');`;
fs.writeFileSync('src/WelcomeScreen.tsx', content.replace(target, replacement));
